# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutomatonGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addStateBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addStateBtn.setObjectName("addStateBtn")
        self.verticalLayout_3.addWidget(self.addStateBtn)
        self.remStateBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.remStateBtn.setObjectName("remStateBtn")
        self.verticalLayout_3.addWidget(self.remStateBtn)
        self.generateBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generateBtn.setObjectName("generateBtn")
        self.verticalLayout_3.addWidget(self.generateBtn)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 6, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.nextOffSpinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nextOffSpinbox.setObjectName("nextOffSpinbox")
        self.verticalLayout_4.addWidget(self.nextOffSpinbox)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.nextOnSpinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nextOnSpinbox.setObjectName("nextOnSpinbox")
        self.verticalLayout_5.addWidget(self.nextOnSpinbox)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.turnOffCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.turnOffCombo.setObjectName("turnOffCombo")
        self.turnOffCombo.addItem("")
        self.turnOffCombo.addItem("")
        self.turnOffCombo.addItem("")
        self.turnOffCombo.addItem("")
        self.verticalLayout_6.addWidget(self.turnOffCombo)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 1, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.turnOnCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.turnOnCombo.setObjectName("turnOnCombo")
        self.turnOnCombo.addItem("")
        self.turnOnCombo.addItem("")
        self.turnOnCombo.addItem("")
        self.turnOnCombo.addItem("")
        self.verticalLayout_7.addWidget(self.turnOnCombo)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 1, 3, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.paintOffCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.paintOffCombo.setObjectName("paintOffCombo")
        self.paintOffCombo.addItem("")
        self.paintOffCombo.addItem("")
        self.verticalLayout_8.addWidget(self.paintOffCombo)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 1, 4, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.paintOnCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.paintOnCombo.setObjectName("paintOnCombo")
        self.paintOnCombo.addItem("")
        self.paintOnCombo.addItem("")
        self.verticalLayout_9.addWidget(self.paintOnCombo)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 1, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.orientCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.orientCombo.setObjectName("orientCombo")
        self.orientCombo.addItem("")
        self.orientCombo.addItem("")
        self.orientCombo.addItem("")
        self.orientCombo.addItem("")
        self.gridLayout_2.addWidget(self.orientCombo, 1, 3, 1, 1)
        self.startStateBox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.startStateBox.setObjectName("startStateBox")
        self.gridLayout_2.addWidget(self.startStateBox, 1, 2, 1, 1)
        self.startYBox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.startYBox.setObjectName("startYBox")
        self.gridLayout_2.addWidget(self.startYBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.startXBox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.startXBox.setObjectName("startXBox")
        self.gridLayout_2.addWidget(self.startXBox, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.namebox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.namebox.setObjectName("namebox")
        self.gridLayout.addWidget(self.namebox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setStyleSheet("font-weight: bold;\n"
"color: rgb(107, 180, 36);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.redSpinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.redSpinbox.setMaximum(1.0)
        self.redSpinbox.setSingleStep(0.05)
        self.redSpinbox.setProperty("value", 0.5)
        self.redSpinbox.setObjectName("redSpinbox")
        self.gridLayout_3.addWidget(self.redSpinbox, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setStyleSheet("color: rgb(239, 41, 41);\n"
"font-weight: bold;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setStyleSheet("font-weight: bold;\n"
"color: rgb(32, 74, 135);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.greenSpinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.greenSpinbox.setMaximum(1.0)
        self.greenSpinbox.setSingleStep(0.05)
        self.greenSpinbox.setProperty("value", 0.5)
        self.greenSpinbox.setObjectName("greenSpinbox")
        self.gridLayout_3.addWidget(self.greenSpinbox, 1, 1, 1, 1)
        self.blueSpinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.blueSpinbox.setMaximum(1.0)
        self.blueSpinbox.setSingleStep(0.05)
        self.blueSpinbox.setProperty("value", 0.5)
        self.blueSpinbox.setObjectName("blueSpinbox")
        self.gridLayout_3.addWidget(self.blueSpinbox, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.stateTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateTable.sizePolicy().hasHeightForWidth())
        self.stateTable.setSizePolicy(sizePolicy)
        self.stateTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stateTable.setObjectName("stateTable")
        self.stateTable.setColumnCount(7)
        self.stateTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.stateTable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setBuddy(self.startXBox)
        self.label_3.setBuddy(self.namebox)
        self.label_2.setBuddy(self.redSpinbox)
        self.label_11.setBuddy(self.nextOffSpinbox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.namebox, self.redSpinbox)
        MainWindow.setTabOrder(self.redSpinbox, self.greenSpinbox)
        MainWindow.setTabOrder(self.greenSpinbox, self.blueSpinbox)
        MainWindow.setTabOrder(self.blueSpinbox, self.startXBox)
        MainWindow.setTabOrder(self.startXBox, self.startYBox)
        MainWindow.setTabOrder(self.startYBox, self.startStateBox)
        MainWindow.setTabOrder(self.startStateBox, self.orientCombo)
        MainWindow.setTabOrder(self.orientCombo, self.nextOffSpinbox)
        MainWindow.setTabOrder(self.nextOffSpinbox, self.nextOnSpinbox)
        MainWindow.setTabOrder(self.nextOnSpinbox, self.turnOffCombo)
        MainWindow.setTabOrder(self.turnOffCombo, self.turnOnCombo)
        MainWindow.setTabOrder(self.turnOnCombo, self.paintOffCombo)
        MainWindow.setTabOrder(self.paintOffCombo, self.paintOnCombo)
        MainWindow.setTabOrder(self.paintOnCombo, self.addStateBtn)
        MainWindow.setTabOrder(self.addStateBtn, self.remStateBtn)
        MainWindow.setTabOrder(self.remStateBtn, self.generateBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addStateBtn.setText(_translate("MainWindow", "&Add State"))
        self.remStateBtn.setText(_translate("MainWindow", "&Remove State"))
        self.generateBtn.setText(_translate("MainWindow", "&Generate"))
        self.label_13.setText(_translate("MainWindow", "Next\n"
"(off)"))
        self.label_15.setText(_translate("MainWindow", "Next\n"
"(on)"))
        self.label_16.setText(_translate("MainWindow", "Turn\n"
"(off)"))
        self.turnOffCombo.setItemText(0, _translate("MainWindow", "None"))
        self.turnOffCombo.setItemText(1, _translate("MainWindow", "Left"))
        self.turnOffCombo.setItemText(2, _translate("MainWindow", "Right"))
        self.turnOffCombo.setItemText(3, _translate("MainWindow", "U-turn"))
        self.label_17.setText(_translate("MainWindow", "Turn\n"
"(on)"))
        self.turnOnCombo.setItemText(0, _translate("MainWindow", "None"))
        self.turnOnCombo.setItemText(1, _translate("MainWindow", "Left"))
        self.turnOnCombo.setItemText(2, _translate("MainWindow", "Right"))
        self.turnOnCombo.setItemText(3, _translate("MainWindow", "U-turn"))
        self.label_18.setText(_translate("MainWindow", "Paint\n"
"(off)"))
        self.paintOffCombo.setItemText(0, _translate("MainWindow", "Off"))
        self.paintOffCombo.setItemText(1, _translate("MainWindow", "On"))
        self.label_14.setText(_translate("MainWindow", "Paint\n"
"(on)"))
        self.paintOnCombo.setItemText(0, _translate("MainWindow", "Off"))
        self.paintOnCombo.setItemText(1, _translate("MainWindow", "On"))
        self.label.setText(_translate("MainWindow", "S&tart:"))
        self.label_7.setText(_translate("MainWindow", "Orientation"))
        self.label_6.setText(_translate("MainWindow", "State Number"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.orientCombo.setItemText(0, _translate("MainWindow", "N"))
        self.orientCombo.setItemText(1, _translate("MainWindow", "E"))
        self.orientCombo.setItemText(2, _translate("MainWindow", "W"))
        self.orientCombo.setItemText(3, _translate("MainWindow", "S"))
        self.startStateBox.setText(_translate("MainWindow", "0"))
        self.startYBox.setText(_translate("MainWindow", "256"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.startXBox.setText(_translate("MainWindow", "512"))
        self.namebox.setText(_translate("MainWindow", "Untitled"))
        self.label_3.setText(_translate("MainWindow", "&Name"))
        self.label_2.setText(_translate("MainWindow", "Co&lor"))
        self.label_9.setText(_translate("MainWindow", "Green (0-1)"))
        self.label_8.setText(_translate("MainWindow", "Red (0-1)"))
        self.label_10.setText(_translate("MainWindow", "Blue (0-1)"))
        self.label_11.setText(_translate("MainWindow", "&State Editor:"))
        item = self.stateTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "State"))
        item = self.stateTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "offNext"))
        item = self.stateTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "onNext"))
        item = self.stateTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "offTurn"))
        item = self.stateTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "onTurn"))
        item = self.stateTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "offPaint"))
        item = self.stateTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "onPaint"))

